### PR TITLE
Fb issue25870

### PR DESCRIPTION
**Pull request by labkey-tgaluhn**

### CODE REVIEW

**Comment by labkey-tgaluhn** [comment]
Susan, could you take a look at the code.

Two changes not related to this bug fix: the test started failing locally for me on repeated runs until I changed the pipeline root to the test temp dir.

I also noticed that the Config web part was showing for all users, even though only Abstraction Admin users had permissions for the links on it.

**Comment by labkey-susanh** [comment]
Looks good to me, Tony. Did you check if we would have any similar problems with any other places we update the report status?

**Comment by labkey-tgaluhn** [comment]
I did not think to check that. Good call.

**Comment by labkey-susanh** [comment]
Assign back to me, Tony, when this is ready to merge.

**Pull request closed without merging**
